#!/usr/bin/env bash

# this script set up networking for the grid vms (and containers) it accepts the following paras
# net_eth<X>=[CIDR;...]
#		where X is [0..5]
# net_r4=[<network>,<gateway>;...]
#		network=(CIDR|default)
#		gateway=(IP|nic)
# net_r6 is same as r4 but should have routes for ipv6
# net_dns=[IP;...]

# Example: net_eth0=10.1.1.3/24;fd39:775a:4846:1::3/64
# 		   net_eth1=302:82a8:705:e5cf:65c6:9fb8:50d1:87c8/64
#		   net_r4=default,10.1.1.1;10.1.0.0/16,10.1.1.1
#		   net_r6=default,fd39:775a:4846:1::1;200::/7,302:82a8:705:e5cf::1
#		   net_dns=8.8.8.8;1.1.1.1;2001:4860:4860::8888

# Note all argument are available to script through env variables already injected
# by the initrd bootstrap. so no need for /proc/cmdline parsing

# set some global settings
sysctl -w net.ipv6.conf.all.accept_ra=2
sysctl -w net.ipv6.conf.all.accept_ra_defrtr=2

setup_nic() {
	nic=$1
	input=$2
	ips=(${input//;/ })

	if ! ip l show "${nic}"; then
		return
	fi

	ip l set "$nic" up
	for ip in ${ips[@]}; do
		ip a a "$ip" dev "$nic"
	done
}

# dns are defined as net_dns=[IP;...]
setup_dns() {
	if [ -z "${net_dns}" ]; then
		return
	fi
	dns=(${net_dns//;/ })

	mkdir -p /etc || true
	if [ -f /etc/resolv.conf ]; then
		rm /etc/resolv.conf
	fi

	for ns in ${dns[@]} ; do
		echo "nameserver ${ns}" >> /etc/resolv.conf
	done
}

# nics are defined as net_eth<X>=[CIDR;...]
setup_nics() {
	# setting up nics
	for index in $(seq 0 5); do
		nic="eth${index}"
		arg="net_${nic}"
		value=$(eval echo \$$arg)
		if [ -z "$value" ]; then
			continue
		fi
		# so we now have nic wit given config data
		setup_nic $nic $value
	done
}

setup_route() {
	ver=$1
	route=$2
	parts=(${route//,/ })

	src=${parts[0]}
	gw=${parts[1]}

	#TODO: validation ?
	via=via
	if [ "${gw:0:3}" = "eth" ]; then
		via=dev
	fi
	ip -$ver r a "${src}" "$via" "${gw}"
}

# routes are in the format [<src>,<dest>;...]
setup_routes() {
	routes=(${net_r4//;/ })
	for route in ${routes[@]}; do
		setup_route 4 $route
	done
	routes=(${net_r6//;/ })
	for route in ${routes[@]}; do
		setup_route 6 $route
	done
}

ip l set lo up

echo "setting up nics"
# setting up nics
setup_nics

echo "setting up routes"
# setting up routes
setup_routes

echo "setting up nameservers"
# setting up dns
setup_dns
