#!/usr/bin/ash

run_hook() {
   echo "mounting pts"
   mkdir -p /dev/pts || true
   mount -t devpts -o rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 devpts /dev/pts

   echo "setting up network"
   bash /setupnetwork
}

run_latehook() {
   echo "settign up environment"
   export HOME=/root
   export PATH=/bin:/sbin:/usr/bin:/usr/sbin

   mkdir -p /new_root/etc || true
   echo "updating resolv.conf"
   cp /etc/resolv.conf /new_root/etc/

   echo "checking for /etc/environment"
   file=/new_root/etc/environment
   if [ ! -f $file ]; then
      return
   fi

   # file exists and is regular file.
   script=$(cat $file | while read line; do
               if [ -n "${line}" ]; then
                  echo "export '${line}'"
               fi
            done)

   eval $script
}

# vim: set ft=sh ts=4 sw=4 et:
